FROM node:20-alpine

WORKDIR /app/ocr_portal_frontend

COPY ocr_portal_frontend/package.json ocr_portal_frontend/package-lock.json* ./
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
