"""add chat_session_docs table (phase 10 follow-up)

Revision ID: 0072a5e4f2a9
Revises: 94a8fdf9f6d2
Create Date: 2026-07-14 16:51:54.692276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0072a5e4f2a9'
down_revision: Union[str, Sequence[str], None] = '94a8fdf9f6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_docs_session_id'), 'chat_session_docs', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_session_docs_user_id'), 'chat_session_docs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_session_docs_user_id'), table_name='chat_session_docs')
    op.drop_index(op.f('ix_chat_session_docs_session_id'), table_name='chat_session_docs')
    op.drop_table('chat_session_docs')
    # ### end Alembic commands ###
